DEFINES += VERSION_BETA

DEFINES += VERSION_MAJOR=3
DEFINES += VERSION_MINOR=0
DEFINES += VERSION_SUB=0
DEFINES += VERSION_GIT=3936
DEFINES += VERSION_YEAR=2013
DEFINES += VERSION_MONTH=6
DEFINES += VERSION_DAY=4
