DEFINES += VERSION_BETA

DEFINES += VERSION_MAJOR=3
DEFINES += VERSION_MINOR=0
DEFINES += VERSION_SUB=0
DEFINES += VERSION_GIT=3674
DEFINES += VERSION_YEAR=2013
DEFINES += VERSION_MONTH=4
DEFINES += VERSION_DAY=4
