#DEFINES += VERSION_BETA

DEFINES += VERSION_MAJOR=3
DEFINES += VERSION_MINOR=0
DEFINES += VERSION_SUB=0
DEFINES += VERSION_GIT=4240
DEFINES += VERSION_YEAR=2013
DEFINES += VERSION_MONTH=7
DEFINES += VERSION_DAY=15
