include_directories(${CMAKE_AGROS_DIRECTORY}3rdparty)
include_directories(${CMAKE_AGROS_DIRECTORY}3rdparty/bson)
include_directories(${CMAKE_AGROS_DIRECTORY}3rdparty/ctemplate)
include_directories(${CMAKE_AGROS_DIRECTORY}3rdparty/libdxfrw)
include_directories(${CMAKE_AGROS_DIRECTORY}3rdparty/paralution)
include_directories(${CMAKE_AGROS_DIRECTORY}3rdparty/qcustomplot)
include_directories(${CMAKE_AGROS_DIRECTORY}3rdparty/qsingleapplication)
include_directories(${CMAKE_AGROS_DIRECTORY}3rdparty/quazip)

include_directories(${CMAKE_AGROS_DIRECTORY}pythonlab)

include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes_common/include)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes_common/include/solvers)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/form)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/space)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/mesh)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/boundary_conditions)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/shapeset)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/function)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/integrals)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/linearizer)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/adapt)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/projections)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/quadrature)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/refinement_selectors)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/views)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/weakform)
include_directories(${CMAKE_AGROS_DIRECTORY}hermes/hermes2d/include/weakform_library)

