PROJECT(agros2d_plugin_{{ID}})
INCLUDE_DIRECTORIES(${CMAKE_AGROS_DIRECTORY}/util)
INCLUDE_DIRECTORIES(${CMAKE_AGROS_DIRECTORY}/pythonlab-library)
INCLUDE_DIRECTORIES(${CMAKE_AGROS_DIRECTORY}/agros2d-library)
INCLUDE_DIRECTORIES(${CMAKE_AGROS_DIRECTORY}/3rdparty)
INCLUDE_DIRECTORIES(${CMAKE_AGROS_DIRECTORY}/3rdparty/bson)
INCLUDE_DIRECTORIES(${CMAKE_AGROS_DIRECTORY}/3rdparty/paralution/src)
EXECUTE_PROCESS(COMMAND "python" "-c" "import distutils.sysconfig; print distutils.sysconfig.get_python_inc()" OUTPUT_VARIABLE PYTHON_INC)
STRING(STRIP ${PYTHON_INC} PYTHON_INC)
INCLUDE_DIRECTORIES(${PYTHON_INC})    
IF(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  INCLUDE_DIRECTORIES(${CMAKE_HOME_DIRECTORY}/3rdparty/ctemplate/linux)
ENDIF()
INCLUDE_DIRECTORIES(.)

SET(SOURCES {{ID}}_interface.cpp {{ID}}_weakform.cpp)
SET(HEADERS {{ID}}_interface.h {{ID}}_weakform.h)

ADD_LIBRARY(${PROJECT_NAME} SHARED ${SOURCES} ${HEADERS})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${QT_LIBRARIES} ${AGROS_UTIL} ${PYTHON_MODLIBS} ${PYTHON_LIB} ${AGROS_LIBRARY} hermes2d hermes_common ${PYTHONLAB_LIBRARY})
INSTALL(TARGETS ${PROJECT_NAME}
				RUNTIME DESTINATION ${CMAKE_AGROS_DIRECTORY}/libs
				LIBRARY DESTINATION ${CMAKE_AGROS_DIRECTORY}/libs
				ARCHIVE DESTINATION ${CMAKE_AGROS_DIRECTORY}/libs)
